### ISSUE TITLE
Look into different board representations

### ISSUE THREAD

**Issue by cradcore** [StaticNomad/PacMan#21]
See if a board represented as a dictionary or array would decrease lookup time and operations

**Comment by StaticNomad** [comment]
@SteelHeart13 are we comfortable with closing this one? I think the implementation of the board object was designed around optimizing performance, correct?

**Comment by SteelHeart13** [comment]
I was going to close this with the implementation of gameboard using numpy arrays and a dictionary representation of state. I am planing on working on this last as an addition to getting the mazes done and helping with the AI when I can.

**Comment by StaticNomad** [comment]
What was your vision for the dictionary representation of state? I'm not sure that changing or updating the gameboard object is going to be possible anymore. The changes to move to a more effective object oriented design has put is in some serious technical debt on the ai algorithm side, and I'm just not sure that I'd be comfortable with pursuing any more changes to the gameboard object as it exists.

**Comment by SteelHeart13** [comment]
If it is going to put too much strain it isn't necessary just was a plan we had. I can move on and focus more on the mazes if that works.

**Comment by SteelHeart13** [comment]
I am going to close this. I think it is a better idea to work more on mazes and the other especially with the little time we have left.
