### ISSUE TITLE
Create multiple mazes in a file

### ISSUE THREAD

**Issue by cradcore** [StaticNomad/PacMan#30]
Pass in an int to determine which maze pacman will use

**Comment by SteelHeart13** [comment]
Do we have a max size for the mazes? I know with the intelligent ghosts it becomes extremely slow at high intelligence levels with large mazes.

**Comment by StaticNomad** [comment]
I put a maximum depth search on ghost intelligence to 8, and I believe @jurentie 's new code for pacman only goes to 3. This has proven to be relatively optimized, and I don't think we'll need to worry much about maximum sizes

**Comment by SteelHeart13** [comment]
Mazes will not have teleport.
