### ISSUE TITLE
Implement Q-Table Learning

### ISSUE THREAD

**Issue by cradcore** [StaticNomad/PacMan#32]

**Comment by StaticNomad** [comment]
PA6 has trainQ and testQ. We will need our own versions of these functions, as well as the helper functions that they need.

**Comment by StaticNomad** [comment]
Score = value

**Comment by StaticNomad** [comment]
This is being worked on in the trainQ-branch, which I've created Pull Request #37 to do.

This is still a work in progress

**Comment by StaticNomad** [comment]
Closed with completion of Pull Request #37
