### ISSUE TITLE
PacMan "run away" behavior

### ISSUE THREAD

**Issue by jurentie** [StaticNomad/PacMan#36]
I think that I have a basic implementation of IDS for PacMan looking for the closest dots, and have a way of  checking to see if there is a ghost too close to the dot to warrant getting that dot, but I'm not sure what is the best way to implement PacMan running away from the ghost.
I was thinking a really simple solution would be to add a check in actions that will check to see if ghost is within a certain distance from the current location and if it is, remove that direction from possible actions all together. This way the next move PacMan makes will always be away from the ghost given a specific distance.
I believe that given this case PacMan will just run away from PacMan until he gets a clear shot to another dot, not in the way of ghosts. What are thoughts on this idea?

**Comment by SteelHeart13** [comment]
So you are thinking something of a miniature iterative deepening search like algorithm?

**Comment by jurentie** [comment]
Well the blood hunter algorithm from Ghost is IDS so I've copied that over, but I've added a case to check for which is the ghost being too near the dot, in which case PacMan should run away. I was thinking of avoiding trying to add any more complication to the intelligent move code, the possible actions returned from actions will omit the direction toward a ghost if the ghost is too close.

**Comment by SteelHeart13** [comment]
So you are looking from the position of Pacman or the dot with the search for the ghost?

**Comment by jurentie** [comment]
Pacman's location

**Comment by StaticNomad** [comment]
I think checking the array is a decent way to do this. I don't think itd be wise to do this inside of the actions function for pacman, but rather implement it within your new intelligentMove in the pacman file.

So you're thinking this:
1. Look at all possible moves.
2. Omit moves that would take us closer to a ghost object.
3. Pick the move that takes us to the next closest dot.

Correct?

**Comment by StaticNomad** [comment]
I believe you are correct in thinking that, over time, Pacman should be able to get all dots just by continually running away. This would require some testing though

**Comment by jurentie** [comment]
So I was planning on implementing this inside of pacman's actions method but now that you mention it I could easily just remove the actions towards the ghost inside the intelligentMove method. I will try that. Thanks!
