### ISSUE TITLE
run from ghost - teleports

### ISSUE THREAD

**Issue by jurentie** [StaticNomad/PacMan#39]
The function runFromGhost() in PacMan.py doesn't know how to properly handle if ghost is on other side of a board and may be going through a teleport. 

For example, pacman might run from ghost through the teleport then think it okay to move around the teleport but when ghost comes through it eats pacman.

**Comment by StaticNomad** [comment]
How viable is creating another depth search (limit 3) where we see how many turns a ghost is away from me (ie pacman)? That would incorporate using teleports

**Comment by StaticNomad** [comment]
Remove teleporting feature from the program.

**Comment by StaticNomad** [comment]
Won't have to remove teleporting feature - just not put 't's in the mazes
