### ISSUE TITLE
Ghost - Intelligent Move

### ISSUE THREAD

**Issue by StaticNomad** [StaticNomad/PacMan#4]
Implement a dynamic IDS AI

**Comment by StaticNomad** [comment]
Pull Request #18 has some beginning intelligence, but Im having some troubles with the IDS. 

However, the Ghost AI to move closest to Pacman is extremely difficult to overcome. It may be sufficient enough for our needs... Im not sure the Ghosts need any AI with this implementation. We can discuss this Tuesday

**Comment by cradcore** [comment]
Only attempt to calculate intelligent move if Pac Man is within maxDepth of the ghost, otherwise choose random move. This should reduce search time by a lot on a larger board

**Comment by StaticNomad** [comment]
This is being worked on in Pull Request #34. The implementation of the board object has caused some issues, but we're resolving them there.

**Comment by StaticNomad** [comment]
Closed!
